name: Charm checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  charm-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Check kubernetes
        working-directory: kubernetes
        run: |
          tox -e lint,unit
      - name: Implement and check kubernetes-extra
        run: |
          uvx --from rust-just just kubernetes-extra
          # Check that the implemented charm matches the one stored in the repo.
          # Exclude uv.lock because 'just kubernetes-extra' adds dependencies,
          # and those dependencies might be newer than for the stored charm.
          git add --all
          git diff --exit-code HEAD -- . ':(exclude)kubernetes-extra/uv.lock'
      - name: Check machine
        working-directory: machine
        run: |
          tox -e lint,unit
