name: Code checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
      - name: Lint
        run: |
          cd .implement
          uvx --from rust-just just lint
          git diff --exit-code  # In case 'uv run' changed the lockfile.
